service: comments-api
frameworkVersion: "2.70.0"

provider:
    name: aws
    runtime: python3.8
    stage: dev
    region: sa-east-1
    lambdaHashingVersion: "20201221"

functions:
    get_comments:
        handler: handler.get_comments
        events:
            - http:
                  path: comments/
                  method: get
                  cors: true

    create_comment:
        handler: handler.create_comment
        events:
            - http:
                  path: comments/
                  method: post
                  cors: true
