service: comments-api
frameworkVersion: "2.70.0"

provider:
    name: aws
    runtime: python3.8
    stage: dev
    region: sa-east-1
    lambdaHashingVersion: "20201221"

functions:
    # Comments module
    - ${file(./modules/comments/functions.yml)}
    # Auth module
    - ${file(./modules/auth/functions.yml)}

layers:
    database:
        path: ./db_layer
        compatibleRuntimes:
            - python3.8
